apiVersion: v1
kind: Service
metadata:
  name: wuda-frontend-service
spec:
  selector:
    app: wuda
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer